export const NEWSPAPERS_LOADING = 'NEWSPAPERS_LOADING';
export const NEWSPAPERS_FAILED = 'NEWSPAPERS_FAILED';
export const ADD_NEWSPAPERS = 'ADD_NEWSPAPERS';
export const MAGAZINES_LOADING = 'MAGAZINES_LOADING';
export const MAGAZINES_FAILED = 'MAGAZINES_FAILED';
export const ADD_MAGAZINES = 'ADD_MAGAZINES';